O:
  color: "#9bbcff"
  brightness: 1.8
B:
  color: "#b9d7ff"
  brightness: 1.6
A:
  color: "#f8f7ff"
  brightness: 1.4
F:
  color: "#fff4ea"
  brightness: 1.3
G:
  color: "#fff4c2"
  brightness: 1.2
K:
  color: "#ffd2a1"
  brightness: 1.0
M:
  color: "#ff6347"
  brightness: 0.8
